### ISSUE TITLE
Lace stalls without error ...

### ISSUE THREAD

**Issue by dietmarpils** [Oshlack/Lace#31]
hello, 
lace stalls always without stopping or giving any error...
the individual fasta-files are generated and then supertranscripts are built (some with the usage of large amounts of RAM, up to 256+128 SWAP), but after a while the program stalls for a long time and after I stop the program with Ctrl-C following output is given: any ideas what goes wrong...

^CProcess ForkPoolWorker-5:
Traceback (most recent call last):
  File "/data/analysis/Dietmar/SW/Supertranscript/Lace-master/Lace.py", line 192, in <module>
    Split(args.GenomeFile,args.ClusterFile,args.cores,args.maxTran,args.outputDir)
  File "/data/analysis/Dietmar/SW/Supertranscript/Lace-master/Lace.py", line 136, in Split
    pool.join()
  File "/data/analysis/Dietmar/SW/Anaconda/Anaconda3/envs/lace/lib/python3.6/multiprocessing/pool.py", line 510, in join
    self._worker_handler.join()
  File "/data/analysis/Dietmar/SW/Anaconda/Anaconda3/envs/lace/lib/python3.6/threading.py", line 1056, in join
    self._wait_for_tstate_lock()
  File "/data/analysis/Dietmar/SW/Anaconda/Anaconda3/envs/lace/lib/python3.6/threading.py", line 1072, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
Traceback (most recent call last):
KeyboardInterrupt
  File "/data/analysis/Dietmar/SW/Anaconda/Anaconda3/envs/lace/lib/python3.6/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/data/analysis/Dietmar/SW/Anaconda/Anaconda3/envs/lace/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/data/analysis/Dietmar/SW/Anaconda/Anaconda3/envs/lace/lib/python3.6/multiprocessing/pool.py", line 108, in worker
    task = get()
  File "/data/analysis/Dietmar/SW/Anaconda/Anaconda3/envs/lace/lib/python3.6/multiprocessing/queues.py", line 343, in get
    res = self._reader.recv_bytes()
  File "/data/analysis/Dietmar/SW/Anaconda/Anaconda3/envs/lace/lib/python3.6/multiprocessing/connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "/data/analysis/Dietmar/SW/Anaconda/Anaconda3/envs/lace/lib/python3.6/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/data/analysis/Dietmar/SW/Anaconda/Anaconda3/envs/lace/lib/python3.6/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
KeyboardInterrupt

**Comment by fgrazom** [comment]
i got the exact same problem, after a couple days running the program simply goes to sleep to never wake up again.
