### ISSUE TITLE
failed install Lace

### ISSUE THREAD

**Issue by Lix1993** [Oshlack/Lace#51]
After install Lace ,：
```bash
conda env create -f environment.yml 
conda activate lace
pip install .
```

running Lace  return s
```python
Lace/Lace_run.py  -h
Traceback (most recent call last):
  File "/share/software/Lace/latest/Lace/Lace_run.py", line 14, in <module>
    from Lace.BuildSuperTranscript import SuperTran
  File "/home/rna/software/miniconda3/envs/lace/lib/python3.9/site-packages/Lace/BuildSuperTranscript.py", line 11, in <module>
    import networkx as nx
  File "/home/rna/software/miniconda3/envs/lace/lib/python3.9/site-packages/networkx/__init__.py", line 114, in <module>
    import networkx.generators
  File "/home/rna/software/miniconda3/envs/lace/lib/python3.9/site-packages/networkx/generators/__init__.py", line 14, in <module>
    from networkx.generators.intersection import *
  File "/home/rna/software/miniconda3/envs/lace/lib/python3.9/site-packages/networkx/generators/intersection.py", line 13, in <module>
    from networkx.algorithms import bipartite
  File "/home/rna/software/miniconda3/envs/lace/lib/python3.9/site-packages/networkx/algorithms/__init__.py", line 16, in <module>
    from networkx.algorithms.dag import *
  File "/home/rna/software/miniconda3/envs/lace/lib/python3.9/site-packages/networkx/algorithms/dag.py", line 23, in <module>
    from fractions import gcd
ImportError: cannot import name 'gcd' from 'fractions' (/home/rna/software/miniconda3/envs/lace/lib/python3.9/fractions.py)
```

**Comment by Lix1993** [comment]
I think this error can be fixed using python=3.5

**Comment by Lix1993** [comment]
my env
```
# This file may be used to create an environment using:
# $ conda create --name <env> --file <this file>
# platform: linux-64
_libgcc_mutex=0.1=conda_forge
_openmp_mutex=4.5=1_gnu
blas=1.1=openblas
blat=36=0
ca-certificates=2020.10.14=0
certifi=2020.6.20=pyhd3eb1b0_3
cycler=0.10.0=py35_0
dbus=1.13.18=hb2f20db_0
decorator=4.4.2=py_0
expat=2.2.10=he6710b0_2
fontconfig=2.13.1=he4413a7_1000
freetype=2.10.4=he06d7ca_0
gettext=0.19.8.1=hf34092f_1004
glib=2.66.2=he1b5a44_0
gst-plugins-base=1.14.5=h0935bb2_2
gstreamer=1.14.5=h36ae1b5_2
icu=58.2=hf484d3e_1000
jpeg=9d=h516909a_0
kiwisolver=1.0.1=py35h2d50403_2
lace=1.14.1=pypi_0
libedit=3.1.20191231=he28a2e2_2
libffi=3.2.1=he1b5a44_1007
libgcc-ng=9.3.0=h5dbcf3e_17
libgfortran=3.0.0=1
libglib=2.66.2=h0dae87d_0
libgomp=9.3.0=h5dbcf3e_17
libiconv=1.16=h516909a_0
libpng=1.6.37=hed695b0_2
libstdcxx-ng=9.3.0=h2ae2ef3_17
libuuid=2.32.1=h14c3975_1000
libxcb=1.14=h7b6447c_0
libxml2=2.9.10=hb55368b_3
matplotlib=3.0.0=py35h5429711_0
ncurses=6.2=he1b5a44_2
networkx=2.3=py_0
numpy=1.15.2=py35_blas_openblashd3ea46f_0
openblas=0.2.20=8
openssl=1.0.2u=h516909a_0
pandas=0.23.4=py35hf8a1672_0
pcre=8.44=he1b5a44_0
pip=20.2.4=py_0
pyparsing=2.4.7=pyh9f0ad1d_0
pyqt=5.9.2=py35h05f1152_2
python=3.5.6=hc3d631a_0
python-dateutil=2.8.1=py_0
pytz=2020.4=pyhd8ed1ab_0
qt=5.9.6=h8703b6f_2
readline=7.0=hf8c457e_1001
setuptools=40.4.3=py35_0
sip=4.19.8=py35hf484d3e_1000
six=1.15.0=pyh9f0ad1d_0
sqlite=3.33.0=h62c20be_0
tk=8.6.10=hed695b0_1
tornado=5.1.1=py35h470a237_0
wheel=0.35.1=pyh9f0ad1d_0
xz=5.2.5=h516909a_1
zlib=1.2.11=h516909a_1010
```

**Comment by ppswang** [comment]
I've encountered the same problem

**Comment by Lix1993** [comment]
@ppswang  

you can use the conda env  i pasted above to fix this
